<?php
require __DIR__ . '/includes/bootstrap.php';
$pageTitle='About Eleganza Rentals | Luxury Car Hire';$pageDescription='Discover the style, service and values behind Eleganza Rentals.';$currentPage='about';
require __DIR__ . '/includes/header.php';$site=settings_all();
?>
<main>
<section class="inner-hero about-hero"><div class="inner-hero-overlay"></div><div class="layout-1350 inner-hero-content"><p class="eyebrow anim-up">About Eleganza Rentals</p><h1><span class="anim-line">Driven by Style.</span><span class="gold-gradient anim-line delay-1">Defined by Service.</span></h1><p class="anim-up delay-2">Premium vehicles, considered details and a direct personal approach to every journey.</p></div></section>
<section class="section"><div class="layout-1350 editorial-grid"><div class="editorial-number reveal">01</div><div class="reveal"><p class="eyebrow">Our Story</p><h2>More Than <span class="gold-gradient">Transportation</span></h2></div><div class="editorial-copy reveal"><p><?= h($site['about_intro']) ?></p><p>Our aim is simple: present desirable cars beautifully, communicate clearly and make the entire experience feel effortless from the first conversation to the final handover.</p></div></div></section>
<section class="section values-section"><div class="layout-1350"><div class="section-heading-row reveal"><div><p class="eyebrow">Our Philosophy</p><h2>The Eleganza <span class="gold-gradient">Standard</span></h2></div><p>A premium experience is created through consistency, presentation and attention to the person behind every booking.</p></div><div class="value-grid"><article class="value-card reveal"><span>Q</span><h3>Quality</h3><p>Focused vehicle selection and a high standard of presentation.</p></article><article class="value-card reveal"><span>S</span><h3>Service</h3><p>Responsive, straightforward communication throughout your enquiry.</p></article><article class="value-card reveal"><span>E</span><h3>Experience</h3><p>Every detail considered so the journey feels as special as the vehicle.</p></article></div></div></section>
<section class="wide-image-section"><div class="layout-1350 wide-image-wrap reveal"><img src="<?= asset('assets/images/about-wide.jpg') ?>" alt="Eleganza luxury vehicle experience"><div class="wide-image-copy"><p class="eyebrow">Italian Style • Premium Experience</p><h2>Elegance in Every Detail.<br><span class="gold-gradient">Excellence on Every Road.</span></h2></div></div></section>
<section class="section final-cta"><div class="layout-1350 final-cta-inner reveal"><div><p class="eyebrow">Experience Eleganza</p><h2>Find Your <span class="gold-gradient">Perfect Drive</span></h2></div><div><p>Explore our current cars or speak directly with the Eleganza Rentals team.</p><div class="cta-actions"><a class="button button-gold" href="<?= url('index.php#cars') ?>">View the Cars</a><a class="button button-outline" href="<?= url('contact.php') ?>">Contact Us</a></div></div></div></section>
</main>
<?php require __DIR__ . '/includes/footer.php'; ?>
