<?php
require dirname(__DIR__) . '/includes/bootstrap.php';require_admin();
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();$action=(string)($_POST['action']??'');$id=(string)($_POST['id']??'');
    if($action==='delete'&&$id){$car=car_by_id($id);delete_car($id);activity('Vehicle deleted',$car?($car['make'].' '.$car['model']):$id);flash('success','Vehicle and its related media were deleted.');}
    if($action==='toggle'&&$id&&($car=car_by_id($id))){$car['published']=empty($car['published']);save_car($car);activity('Vehicle publication changed',$car['model']);flash('success','Publication status updated.');}
    redirect(url('admin/cars.php'));
}
$adminPageTitle='Vehicles';$adminCurrent='cars';$cars=cars_all(false);require dirname(__DIR__) . '/includes/admin-header.php';
?>
<section class="admin-panel"><div class="admin-panel-header"><div><h2>Vehicle Management</h2><p class="admin-muted">Add cars, update exact prices, change descriptions and control whether a car appears publicly.</p></div><a class="admin-button" href="<?=url('admin/car-form.php')?>">Add Vehicle</a></div>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Image</th><th>Vehicle</th><th>Starting Price</th><th>Default Status</th><th>Published</th><th>Actions</th></tr></thead><tbody><?php foreach($cars as $car):$cover=cover_media($car);?><tr><td><?php if($cover):?><img class="table-image" src="<?=asset($cover['path'])?>" alt=""><?php else:?><span>—</span><?php endif;?></td><td><strong><?=h($car['make'].' '.$car['model'])?></strong><br><span class="admin-muted"><?=h($car['year'].' • '.$car['slug'])?></span></td><td><?=format_money($car['starting_price'])?></td><td><span class="status-badge status-<?=h($car['default_status'])?>"><?=h(status_label($car['default_status']))?></span></td><td><?=!empty($car['published'])?'Yes':'No'?></td><td><div class="table-actions"><a class="admin-button secondary small" href="<?=url('admin/car-form.php?id='.rawurlencode($car['id']))?>">Edit</a><a class="admin-button secondary small" href="<?=url('admin/media.php?car_id='.rawurlencode($car['id']))?>">Media</a><form method="post"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($car['id'])?>"><input type="hidden" name="action" value="toggle"><button class="admin-button secondary small" type="submit"><?=!empty($car['published'])?'Unpublish':'Publish'?></button></form><form method="post"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($car['id'])?>"><input type="hidden" name="action" value="delete"><button class="admin-button danger small" type="submit" data-confirm="Delete this vehicle and all uploaded media?">Delete</button></form></div></td></tr><?php endforeach;?></tbody></table></div></section>
<?php require dirname(__DIR__) . '/includes/admin-footer.php'; ?>
