<?php
require dirname(__DIR__) . '/includes/bootstrap.php';
$adminPageTitle='Dashboard';$adminCurrent='dashboard';
$cars=cars_all(false);$enquiries=enquiries_all();$available=0;$onHire=0;
foreach($cars as $car){$st=car_status($car);if($st['available'])$available++;if($st['key']==='on_hire')$onHire++;}
$newMessages=count(array_filter($enquiries,fn($e)=>($e['status']??'new')==='new'));
$activity=array_reverse(array_slice(data_read('activity',[]),-8));
require dirname(__DIR__) . '/includes/admin-header.php';
?>
<div class="stats-grid"><div class="stat-card"><span>Total Vehicles</span><strong><?=count($cars)?></strong></div><div class="stat-card"><span>Available Now</span><strong><?=$available?></strong></div><div class="stat-card"><span>On Hire</span><strong><?=$onHire?></strong></div><div class="stat-card"><span>New Messages</span><strong><?=$newMessages?></strong></div></div>
<div class="admin-grid"><section class="admin-panel"><div class="admin-panel-header"><h2>Vehicle Status</h2><a class="admin-button small" href="<?=url('admin/availability.php')?>">Manage Availability</a></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Vehicle</th><th>Status</th><th>Return</th><th>Action</th></tr></thead><tbody><?php foreach($cars as $car):$status=car_status($car);?><tr><td><strong><?=h($car['make'].' '.$car['model'])?></strong><br><span class="admin-muted"><?=h($car['year'])?></span></td><td><span class="status-badge status-<?=h($status['key'])?>"><?=h($status['label'])?></span></td><td><?=h($status['return_at']?format_date_time($status['return_at']):'—')?></td><td><a class="admin-button secondary small" href="<?=url('admin/car-form.php?id='.rawurlencode($car['id']))?>">Edit</a></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="admin-panel"><div class="admin-panel-header"><h2>Latest Messages</h2><a class="admin-button secondary small" href="<?=url('admin/enquiries.php')?>">View All</a></div><?php if(!$enquiries):?><div class="empty-state">No enquiries yet.</div><?php else:?><div class="simple-list"><?php foreach(array_slice($enquiries,0,6) as $item):?><a class="simple-list-item" href="<?=url('admin/enquiry.php?id='.rawurlencode($item['id']))?>"><div><strong><?=h($item['name'])?></strong><br><span><?=h($item['vehicle_name'])?></span></div><span><?=h((new DateTimeImmutable($item['created_at']))->format('d M, H:i'))?></span></a><?php endforeach;?></div><?php endif;?></section></div>
<div class="admin-grid"><section class="admin-panel"><div class="admin-panel-header"><h2>Quick Actions</h2></div><div class="table-actions"><a class="admin-button" href="<?=url('admin/car-form.php')?>">Add Vehicle</a><a class="admin-button secondary" href="<?=url('admin/media.php')?>">Upload Media</a><a class="admin-button secondary" href="<?=url('admin/availability.php')?>">Block Dates</a><a class="admin-button secondary" href="<?=url('admin/settings.php')?>">Email Setup</a></div></section><section class="admin-panel"><div class="admin-panel-header"><h2>Recent Activity</h2></div><?php if(!$activity):?><div class="empty-state">No activity recorded.</div><?php else:?><div class="activity-list"><?php foreach($activity as $log):?><div class="activity-item"><div><strong><?=h($log['action'])?></strong><br><span><?=h($log['detail'])?></span></div><span><?=h((new DateTimeImmutable($log['created_at']))->format('d M, H:i'))?></span></div><?php endforeach;?></div><?php endif;?></section></div>
<?php require dirname(__DIR__) . '/includes/admin-footer.php'; ?>
